//! `aval hook install` — put the decision heads in front of an agent.
//!
//! A corpus that resolves is only half the point. The other half is that
//! whatever is about to write code starts from what was decided rather than
//! from what it can infer, which is the failure this whole tool exists to
//! treat: six copies of a design-system rule in six `CLAUDE.md` files, one of
//! them already wrong.
//!
//! Modelled on `duro hook install`, deliberately, because that pattern is
//! proven across several repositories and a second shape would be a second
//! thing to learn. Two differences, both because this payload is local:
//!
//! - **No cache, no TTL, no staging file.** duro fetches a catalog over the
//!   network, so it caches. `aval heads` reads a directory this repository
//!   already contains, on the same code path the pre-commit gate runs, so
//!   caching would only add a way to be stale.
//! - **Nothing to add to `.gitignore`**, because nothing is written at runtime.
//!
//! The preamble's last paragraph is there because of a specific mistake made
//! while building this. Two sync transports were live in one repository, each
//! documented as current, and the conversion recorded them as one decision per
//! mode. They were not: one had replaced the other and the code had not caught
//! up. The evidence in the repository was equally consistent with both
//! readings, so no amount of reading it harder would have helped — the fix is
//! to ask, and the preamble is where that instruction reaches an agent at the
//! moment it matters.

use aval_core::json::{self, Json};
use std::path::{Path, PathBuf};

pub const SCRIPT_PATH: &str = ".claude/hooks/aval-heads.sh";
pub const SETTINGS_PATH: &str = ".claude/settings.json";
/// Repo-specific caveats. Appended by the hook, never touched by install.
pub const NOTES_PATH: &str = ".claude/aval-hook.local.md";

/// The command written into settings. Also the marker `install` matches on, so
/// a hand-edited variant is rewritten in place rather than duplicated.
pub const COMMAND: &str = "sh .claude/hooks/aval-heads.sh";

pub const SCRIPT: &str = r#"#!/bin/sh
# Generated by `aval hook install`. Do not edit — regeneration overwrites it.
#
# Prints the current decision heads at session start, so whatever is about to
# write code starts from what was decided rather than from what it can infer.
#
# Repo-specific caveats belong in .claude/aval-hook.local.md, which this
# appends and which `aval hook install` never touches.

notes=".claude/aval-hook.local.md"

# No aval, no output, no failure. A session must not depend on a tool the
# person who started it has not installed.
command -v aval >/dev/null 2>&1 || exit 0

# Silent when there is nothing to say: no registry here, or a corpus that does
# not resolve. `heads` renders nothing rather than a partial projection, and
# reporting a broken corpus is the gate's job, not this one's.
heads=$(aval heads 2>/dev/null) || exit 0
[ -n "$heads" ] || exit 0

cat <<'PREAMBLE'
ARCHITECTURE DECISIONS — these are decided. Do not re-litigate them, and do
not restate them in another file; that is the duplication this corpus exists
to end.

  aval resolve <key> [--scope S]   what is decided, with an exit code
  aval show <record>               one record, and whether it still holds
  aval history <key>               how it got here — history, not authority

To change one, write a record that `replaces` it. Editing the old record is
not how supersession works here, and `aval check` will say so.

What is deployed is not what was decided. Two implementations both running is
not evidence that both were chosen — it is equally consistent with one having
replaced the other and the code not having caught up. Ask someone; do not
infer a decision from what is running.
PREAMBLE

echo
printf '%s\n' "$heads"

if [ -s "$notes" ]; then
  echo
  cat "$notes"
fi
"#;

pub struct Change {
    pub path: String,
    pub status: Status,
    pub detail: &'static str,
}

#[derive(PartialEq, Eq)]
pub enum Status {
    Written,
    Unchanged,
    /// `--check` only: this would have been written.
    Stale,
}

pub struct Report {
    pub changes: Vec<Change>,
    /// Paths git would ignore, so the hook would work here and ship to nobody.
    pub ignored: Vec<String>,
}

impl Report {
    pub fn stale(&self) -> usize {
        self.changes
            .iter()
            .filter(|c| c.status == Status::Stale)
            .count()
    }
}

pub enum Error {
    /// `.claude/settings.json` exists and is not JSON. Never clobbered.
    SettingsUnparseable(String),
    Io(String),
}

fn read(p: &Path) -> Option<String> {
    std::fs::read_to_string(p).ok()
}

/// The settings file with our entry present and correct, or `None` when it
/// already is.
///
/// Parse, mutate, re-serialise — so keys this tool knows nothing about survive.
/// It does reorder them: this crate's JSON object is a sorted map, chosen so
/// that `--json` output is byte-stable. The reordering is one-time and stable,
/// and the alternative was making every `--json` key order depend on
/// construction order instead.
fn next_settings(current: Option<&str>) -> Result<Option<String>, Error> {
    let mut root = match current {
        None => Json::obj(),
        Some(s) if s.trim().is_empty() => Json::obj(),
        Some(s) => json::parse(s).map_err(Error::SettingsUnparseable)?,
    };

    let ours = Json::obj().set(
        "hooks",
        vec![Json::obj().set("type", "command").set("command", COMMAND)],
    );

    let hooks = root.get("hooks").cloned().unwrap_or_else(Json::obj);
    let existing: Vec<Json> = hooks
        .get("SessionStart")
        .and_then(|s| s.as_arr())
        .map(|a| a.to_vec())
        .unwrap_or_default();

    // Match on the script path rather than the whole command, so
    // `bash ./.claude/hooks/aval-heads.sh` is corrected rather than joined by a
    // second entry that does the same thing.
    let mine = |g: &Json| -> bool {
        g.get("hooks")
            .and_then(|h| h.as_arr())
            .map(|hs| {
                hs.iter().any(|e| {
                    e.get("command")
                        .and_then(|c| c.as_str())
                        .is_some_and(|c| c.contains(SCRIPT_PATH))
                })
            })
            .unwrap_or(false)
    };

    let already = existing.iter().any(&mine);
    if already && existing.iter().filter(|g| mine(g)).all(|g| g == &ours) {
        return Ok(None);
    }

    let mut next: Vec<Json> = existing.into_iter().filter(|g| !mine(g)).collect();
    next.push(ours);

    let hooks = hooks.set("SessionStart", next);
    root = root.set("hooks", hooks);
    let mut out = String::new();
    root.write_pretty(&mut out, 0);
    out.push('\n');
    Ok(Some(out))
}

pub fn install(root: &Path, check: bool) -> Result<Report, Error> {
    let mut changes = Vec::new();
    let at = |p: &str| -> PathBuf { root.join(p) };

    let mut record =
        |path: &str, next: Option<String>, detail: &'static str| -> Result<(), Error> {
            let Some(body) = next else {
                changes.push(Change {
                    path: path.to_string(),
                    status: Status::Unchanged,
                    detail: "already up to date",
                });
                return Ok(());
            };
            if check {
                changes.push(Change {
                    path: path.to_string(),
                    status: Status::Stale,
                    detail,
                });
                return Ok(());
            }
            let p = at(path);
            if let Some(d) = p.parent() {
                std::fs::create_dir_all(d)
                    .map_err(|e| Error::Io(format!("{}: {}", d.display(), e)))?;
            }
            std::fs::write(&p, body).map_err(|e| Error::Io(format!("{}: {}", p.display(), e)))?;
            changes.push(Change {
                path: path.to_string(),
                status: Status::Written,
                detail,
            });
            Ok(())
        };

    // Everything is decided before anything is written. An unreadable settings
    // file must stop the install with the repository untouched — not after a
    // script has already been dropped into it, which is what a write-as-you-go
    // order produced and a test caught.
    let have_script = read(&at(SCRIPT_PATH));
    let script_detail = if have_script.is_none() {
        "created"
    } else {
        "regenerated"
    };
    // The script's own bytes are its version. There is no stamp to compare and
    // nothing to migrate: an older script differs, so it is regenerated.
    let next_script = if have_script.as_deref() == Some(SCRIPT) {
        None
    } else {
        Some(SCRIPT.to_string())
    };

    let have_settings = read(&at(SETTINGS_PATH));
    let settings_detail = if have_settings.is_none() {
        "created"
    } else {
        "merged"
    };
    let next_settings_body = next_settings(have_settings.as_deref())?;

    record(SCRIPT_PATH, next_script, script_detail)?;
    record(SETTINGS_PATH, next_settings_body, settings_detail)?;

    let ignored = if check {
        Vec::new()
    } else {
        ignored_trackables(root)
    };
    Ok(Report { changes, ignored })
}

/// Paths git is ignoring, best effort.
///
/// A repository that excludes `.claude` — common, and often written as
/// `.claude/*` with a few negations — silently drops the files just written.
/// The hook then works for whoever ran the command and for nobody else.
fn ignored_trackables(root: &Path) -> Vec<String> {
    let out = std::process::Command::new("git")
        .args(["check-ignore", "--", SCRIPT_PATH, SETTINGS_PATH, NOTES_PATH])
        .current_dir(root)
        .output();
    match out {
        // Exit 1 means nothing matched, which is the ordinary case. No git, or
        // not a repository yet, is not this command's business to report.
        Ok(o) => String::from_utf8_lossy(&o.stdout)
            .lines()
            .filter(|l| !l.trim().is_empty())
            .map(|l| l.trim().to_string())
            .collect(),
        Err(_) => Vec::new(),
    }
}
