//! `aval.pack`: one repository's declarations, in a form another can read.
//!
//! # What is in it, and what deliberately is not
//!
//! A pack carries **declarations** — the key definitions, the scope
//! vocabulary, and every record's frontmatter. It does not carry `HEADS.md`,
//! and it does not carry prose.
//!
//! `HEADS.md` is derived state. `no-manual-index` exists because copied
//! derived state has no invariant behind it: nothing knows that a row which
//! should have been there is missing. Vendoring the projection would recreate
//! exactly that failure across repositories instead of inside one. Vendoring
//! the declarations means the consumer computes the heads itself, from the
//! same graph, with the same code — so a superseded decision cannot survive
//! the trip.
//!
//! Prose is left behind because a record's body is written for the repository
//! that owns the decision, its citations point at that repository's files, and
//! the whole of it is an order of magnitude larger than the frontmatter that
//! actually answers a question.
//!
//! # Nothing here executes
//!
//! This is the difference from `amont`'s packs, and it is why there is no
//! trust prompt to match `amont trust`. That tool vendors *commands*, so
//! consent has to be taken per machine and re-taken whenever the text changes.
//! A pack vendors *decisions*. Nothing in this file is ever run, so the review
//! gate is the pull request that adds it — which is where a change of
//! architectural direction belongs anyway.
//!
//! # Identity
//!
//! A pack's records keep their own ids and are qualified with the pack's name
//! on the way in: `ADR-0002` from the `decisions` pack is `decisions:ADR-0002`
//! here. Two repositories both numbering from one would otherwise collide, and
//! the collision would look like `id-unique` firing on a corpus whose author
//! wrote neither id. The qualification happens at load, not at vendor time, so
//! the file on disk stays byte-identical to what the producer published.

use crate::model::*;
use crate::yaml::{self, Node};

/// What a producing repository publishes, at its root.
pub const FILE: &str = "aval.pack";

pub const BANNER: &str = "Generated by `aval pack --write`. Do not edit.";

const PACK_FIELDS: &[&str] = &["aval", "scopes", "keys", "records"];
const RECORD_FIELDS: &[&str] = &["id", "status", "decisions"];

fn a(check: &'static str, msg: impl Into<String>) -> Finding {
    Finding::new(Layer::A, check, msg)
}

/// `<pack>:<id>`, the form a vendored record is referred to by.
pub fn qualify(pack: &str, id: &str) -> String {
    format!("{}:{}", pack, id)
}

/// Whether a name can be a pack: it becomes an id prefix, so it has to be as
/// restricted as an id is, and it must not itself contain the separator.
pub fn bad_name(name: &str) -> Option<String> {
    if name.is_empty() {
        return Some("a pack name cannot be empty".into());
    }
    if name.len() > 32 {
        return Some(format!("pack name `{}` is longer than 32 characters", name));
    }
    if !name.starts_with(|c: char| c.is_ascii_alphabetic()) {
        return Some(format!("pack name `{}` must start with a letter", name));
    }
    if let Some(c) = name
        .chars()
        .find(|c| !(c.is_ascii_alphanumeric() || "._-".contains(*c)))
    {
        return Some(format!(
            "pack name `{}` carries `{}`; a name holds letters, digits, `.`, `_` and `-`",
            name, c
        ));
    }
    None
}

// --- writing ---------------------------------------------------------------

/// Emit a scalar that reads back as itself.
///
/// Always quoted, never bare. A bare `true` comes back a boolean, a bare `[a]`
/// a sequence, and a bare value holding `: ` is ambiguous with a mapping — and
/// the point of this file is that what the producer decided is what the
/// consumer reads. Quoting unconditionally costs two bytes and removes the
/// whole class.
fn out(s: &str) -> String {
    format!("\"{}\"", s.replace('"', "\\\""))
}

/// The declarations of a corpus, as the text a consumer will vendor.
///
/// Deterministic and sorted, for the same reason `project::render` is: the file
/// is regenerated by a command and compared by a check, so any ordering that
/// depended on how the directory happened to be read would be a diff nobody
/// caused.
pub fn render(c: &Corpus) -> String {
    let mut o = String::new();
    o.push_str("# ");
    o.push_str(BANNER);
    o.push('\n');
    o.push_str(&format!("aval: {}\n", out(env!("CARGO_PKG_VERSION"))));

    let mut scopes: Vec<&str> = c.registry.scopes.iter().map(String::as_str).collect();
    scopes.sort();
    o.push_str("scopes:\n");
    for s in &scopes {
        o.push_str(&format!("  - {}\n", out(s)));
    }

    let mut keys: Vec<&KeyDef> = c.registry.keys.iter().collect();
    keys.sort_by(|x, y| x.name.cmp(&y.name));
    o.push_str("keys:\n");
    for k in &keys {
        o.push_str(&format!("  {}:\n", out(&k.name)));
        if let Some(d) = &k.description {
            o.push_str(&format!("    description: {}\n", out(d)));
        }
        if let Some(list) = &k.scopes {
            o.push_str("    scopes:\n");
            let mut v: Vec<&str> = list.iter().map(String::as_str).collect();
            v.sort();
            for s in &v {
                o.push_str(&format!("      - {}\n", out(s)));
            }
        }
    }

    let mut adrs: Vec<&Adr> = c.adrs.iter().collect();
    adrs.sort_by(|x, y| x.id.cmp(&y.id));
    o.push_str("records:\n");
    for r in &adrs {
        o.push_str(&format!("  - id: {}\n", out(&r.id)));
        o.push_str(&format!(
            "    status: {}\n",
            out(match r.status {
                Status::Draft => "draft",
                Status::Accepted => "accepted",
            })
        ));
        o.push_str("    decisions:\n");
        for e in &r.decisions {
            o.push_str(&format!("      - key: {}\n", out(&e.key)));
            if e.scope != DEFAULT_SCOPE {
                o.push_str(&format!("        scope: {}\n", out(&e.scope)));
            }
            match &e.kind {
                EntryKind::Choice(ch) => o.push_str(&format!("        choice: {}\n", out(ch))),
                EntryKind::Retire => o.push_str("        retire: true\n"),
            }
            if e.first {
                o.push_str("        first: true\n");
            }
            if !e.replaces.is_empty() {
                o.push_str("        replaces:\n");
                for p in &e.replaces {
                    o.push_str(&format!("          - {}\n", out(p)));
                }
            }
            if let Some(ov) = &e.overrides {
                o.push_str(&format!("        overrides: {}\n", out(ov)));
            }
            if let Some(rs) = &e.reason {
                o.push_str(&format!("        reason: {}\n", out(rs)));
            }
        }
    }
    o
}

// --- reading ---------------------------------------------------------------

/// One pack, read and qualified.
#[derive(Debug, Clone)]
pub struct Pack {
    pub name: String,
    pub scopes: Vec<String>,
    pub keys: Vec<KeyDef>,
    pub adrs: Vec<Adr>,
}

fn want(node: &Node, key: &str, file: &str, out: &mut Vec<Finding>) -> Option<String> {
    let v = node.get(key)?;
    match v.as_str() {
        Some(s) => Some(s.to_string()),
        None => {
            out.push(
                a(
                    "pack-parses",
                    format!("`{}` must be a string, found {}", key, v.kind()),
                )
                .at(file, v.line),
            );
            None
        }
    }
}

fn want_list(node: &Node, key: &str, file: &str, out: &mut Vec<Finding>) -> Vec<String> {
    let Some(v) = node.get(key) else {
        return Vec::new();
    };
    let Some(items) = v.as_seq() else {
        out.push(
            a(
                "pack-parses",
                format!("`{}` must be a list, found {}", key, v.kind()),
            )
            .at(file, v.line),
        );
        return Vec::new();
    };
    items
        .iter()
        .filter_map(|i| match i.as_str() {
            Some(s) => Some(s.to_string()),
            None => {
                out.push(
                    a(
                        "pack-parses",
                        format!("`{}` must hold strings, found {}", key, i.kind()),
                    )
                    .at(file, i.line),
                );
                None
            }
        })
        .collect()
}

fn flag(node: &Node, key: &str) -> bool {
    node.get(key).and_then(|v| v.as_bool()).unwrap_or(false)
}

/// Read a vendored pack.
///
/// `file` is the vendored path in *this* repository, so every finding points
/// at something the reader can open. `name` is the pack's name, which becomes
/// the id prefix.
///
/// A pack is refused whole. A half-read pack is a graph that is missing edges
/// nobody removed: whatever a dropped record superseded comes back as a head,
/// and `resolve` answers `active` with a decision that was replaced. That is
/// the failure this tool exists to prevent, so it must not be reachable by a
/// file being slightly wrong.
pub fn parse(file: &str, name: &str, src: &str) -> Result<Pack, Vec<Finding>> {
    let mut out = Vec::new();
    if let Some(m) = bad_name(name) {
        return Err(vec![a("pack-parses", m).in_file(file)]);
    }
    let doc = match yaml::parse(src) {
        Ok(d) => d,
        Err(e) => return Err(vec![a("pack-parses", e.message).at(file, e.line)]),
    };
    if doc.as_map().is_none() {
        return Err(vec![a(
            "pack-parses",
            format!("a pack must be a mapping, found {}", doc.kind()),
        )
        .in_file(file)]);
    }
    for (k, v) in doc.as_map().unwrap() {
        if !PACK_FIELDS.contains(&k.as_str()) {
            out.push(a("pack-parses", format!("unknown pack field `{}`", k)).at(file, v.line));
        }
    }

    let scopes = want_list(&doc, "scopes", file, &mut out);
    let mut keys = Vec::new();
    if let Some(k) = doc.get("keys") {
        match k.as_map() {
            None if k.is_null() => {}
            None => out.push(
                a(
                    "pack-parses",
                    format!("`keys` must be a mapping, found {}", k.kind()),
                )
                .at(file, k.line),
            ),
            Some(entries) => {
                for (n, def) in entries {
                    let (description, key_scopes) = if def.is_null() {
                        (None, None)
                    } else {
                        (
                            want(def, "description", file, &mut out),
                            def.get("scopes")
                                .map(|_| want_list(def, "scopes", file, &mut out)),
                        )
                    };
                    keys.push(KeyDef {
                        name: n.clone(),
                        description,
                        scopes: key_scopes,
                    });
                }
            }
        }
    }

    // Every id in the pack, so an intra-pack reference can be told from a
    // dangling one before it is qualified. A reference that names nothing must
    // stay dangling rather than becoming a prefixed id that names nothing —
    // the finding would then blame a name the producer never wrote.
    let mut ids: Vec<String> = Vec::new();
    if let Some(rs) = doc.get("records").and_then(|r| r.as_seq()) {
        for r in rs {
            if let Some(i) = r.get("id").and_then(|n| n.as_str()) {
                ids.push(i.to_string());
            }
        }
    }
    let q = |r: &str| -> String {
        if ids.iter().any(|i| i == r) {
            qualify(name, r)
        } else {
            r.to_string()
        }
    };

    let mut adrs = Vec::new();
    match doc.get("records") {
        None => out.push(a("pack-parses", "missing `records`").in_file(file)),
        Some(r) if r.is_null() => {}
        Some(r) => match r.as_seq() {
            None => out.push(
                a(
                    "pack-parses",
                    format!("`records` must be a list, found {}", r.kind()),
                )
                .at(file, r.line),
            ),
            Some(items) => {
                for it in items {
                    if let Some(adr) = record(it, file, name, &q, &mut out) {
                        adrs.push(adr);
                    }
                }
            }
        },
    }

    if out.is_empty() {
        Ok(Pack {
            name: name.to_string(),
            scopes,
            keys,
            adrs,
        })
    } else {
        Err(out)
    }
}

fn record(
    node: &Node,
    file: &str,
    pack: &str,
    q: &dyn Fn(&str) -> String,
    out: &mut Vec<Finding>,
) -> Option<Adr> {
    let before = out.len();
    if node.as_map().is_none() {
        out.push(
            a(
                "pack-parses",
                format!("each record must be a mapping, found {}", node.kind()),
            )
            .at(file, node.line),
        );
        return None;
    }
    for (k, v) in node.as_map().unwrap() {
        if !RECORD_FIELDS.contains(&k.as_str()) {
            out.push(a("pack-parses", format!("unknown record field `{}`", k)).at(file, v.line));
        }
    }
    let id = want(node, "id", file, out);
    if id.is_none() {
        out.push(a("pack-parses", "a record is missing `id`").at(file, node.line));
    }
    let status = match want(node, "status", file, out) {
        Some(s) => match Status::parse(&s) {
            Some(st) => st,
            None => {
                out.push(
                    a("pack-parses", format!("`status: {}` is not a status", s))
                        .at(file, node.line),
                );
                Status::Draft
            }
        },
        None => {
            out.push(a("pack-parses", "a record is missing `status`").at(file, node.line));
            Status::Draft
        }
    };

    let mut decisions = Vec::new();
    if let Some(d) = node.get("decisions").and_then(|d| d.as_seq()) {
        for e in d {
            let key = match want(e, "key", file, out) {
                Some(k) => k,
                None => {
                    out.push(a("pack-parses", "a decision is missing `key`").at(file, e.line));
                    continue;
                }
            };
            let kind = match want(e, "choice", file, out) {
                Some(c) => EntryKind::Choice(c),
                None if flag(e, "retire") => EntryKind::Retire,
                None => {
                    out.push(
                        a(
                            "pack-parses",
                            "a decision has neither `choice` nor `retire`",
                        )
                        .at(file, e.line),
                    );
                    continue;
                }
            };
            decisions.push(Entry {
                key,
                scope: want(e, "scope", file, out).unwrap_or_else(|| DEFAULT_SCOPE.to_string()),
                kind,
                first: flag(e, "first"),
                replaces: want_list(e, "replaces", file, out)
                    .iter()
                    .map(|r| q(r))
                    .collect(),
                overrides: want(e, "overrides", file, out).map(|o| q(&o)),
                reason: want(e, "reason", file, out),
                line: e.line,
            });
        }
    }

    if out.len() != before {
        return None;
    }
    Some(Adr {
        id: qualify(pack, &id?),
        status,
        decisions,
        // The vendored file, because that is the file in this repository a
        // reader can open. The record's own document is in another one.
        file: file.to_string(),
        pack: Some(pack.to_string()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn corpus() -> Corpus {
        Corpus {
            registry: Registry {
                dir: "docs/adr".into(),
                sources: Vec::new(),
                packs: Vec::new(),
                scopes: vec!["effect-stack".into()],
                keys: vec![KeyDef {
                    name: "stack.sql-layer".into(),
                    description: Some("The SQL access layer".into()),
                    scopes: Some(vec!["effect-stack".into()]),
                }],
            },
            adrs: vec![Adr {
                id: "ADR-0002".into(),
                status: Status::Accepted,
                decisions: vec![Entry {
                    key: "stack.sql-layer".into(),
                    scope: "effect-stack".into(),
                    kind: EntryKind::Choice("@effect/sql".into()),
                    first: true,
                    replaces: Vec::new(),
                    overrides: None,
                    reason: Some("Kysely # was the alternative".into()),
                    line: 5,
                }],
                file: "docs/adr/0002-x.md".into(),
                pack: None,
            }],
        }
    }

    #[test]
    fn a_pack_round_trips() {
        let text = render(&corpus());
        let p = parse(".adr/packs/fleet.yaml", "fleet", &text).expect("parses");
        assert_eq!(p.scopes, ["effect-stack"]);
        assert_eq!(p.keys[0].name, "stack.sql-layer");
        assert_eq!(
            p.keys[0].scopes.as_deref(),
            Some(&["effect-stack".into()][..])
        );
        assert_eq!(p.adrs[0].id, "fleet:ADR-0002");
        assert!(p.adrs[0].is_vendored());
        let e = &p.adrs[0].decisions[0];
        assert_eq!(e.choice(), Some("@effect/sql"));
        assert_eq!(e.scope, "effect-stack");
        assert!(e.first);
        // The value carries ` # `, which an unquoted scalar would have lost to
        // the comment stripper. Quoting every value is what keeps it.
        assert_eq!(e.reason.as_deref(), Some("Kysely # was the alternative"));
    }

    #[test]
    fn hostile_values_survive_the_trip() {
        let mut c = corpus();
        for (i, v) in [
            "a|b",
            "A\\|B",
            "back\\slash",
            "quote\"inside",
            "true",
            "[not, a, list]",
            "colon: here",
            "  padded  ",
            "# leading hash",
        ]
        .iter()
        .enumerate()
        {
            let mut r = c.adrs[0].clone();
            r.id = format!("ADR-{:04}", 100 + i);
            r.decisions[0].kind = EntryKind::Choice((*v).to_string());
            c.adrs.push(r);
        }
        c.adrs.remove(0);
        let text = render(&c);
        let p = parse("p.yaml", "fleet", &text).expect("parses");
        let got: Vec<&str> = p
            .adrs
            .iter()
            .filter_map(|r| r.decisions[0].choice())
            .collect();
        assert_eq!(
            got,
            [
                "a|b",
                "A\\|B",
                "back\\slash",
                "quote\"inside",
                "true",
                "[not, a, list]",
                "colon: here",
                "  padded  ",
                "# leading hash",
            ]
        );
    }

    #[test]
    fn intra_pack_references_are_qualified_and_dangling_ones_are_not() {
        let mut c = corpus();
        let mut r = c.adrs[0].clone();
        r.id = "ADR-0003".into();
        r.decisions[0].first = false;
        r.decisions[0].replaces = vec!["ADR-0002".into(), "ADR-9999".into()];
        c.adrs.push(r);
        let p = parse("p.yaml", "fleet", &render(&c)).expect("parses");
        let second = p.adrs.iter().find(|x| x.id == "fleet:ADR-0003").unwrap();
        assert_eq!(
            second.decisions[0].replaces,
            ["fleet:ADR-0002", "ADR-9999"],
            "a reference that names nothing must stay as written, or the \
             finding would blame a name the producer never used"
        );
    }

    #[test]
    fn a_pack_is_refused_whole_on_one_bad_record() {
        let text = render(&corpus()).replace("\"accepted\"", "\"superseded\"");
        let e = parse("p.yaml", "fleet", &text).unwrap_err();
        assert!(e[0].message.contains("is not a status"), "{:?}", e);
    }

    #[test]
    fn a_pack_name_must_be_usable_as_an_id_prefix() {
        assert!(bad_name("decisions").is_none());
        assert!(bad_name("").is_some());
        assert!(bad_name("2fleet").is_some());
        // The separator itself, which would make the prefix ambiguous.
        assert!(bad_name("a:b").is_some());
    }
}
