//! `aval.pack`: one repository's declarations, in a form another can read.
//!
//! # What is in it, and what deliberately is not
//!
//! A pack carries **declarations** — the key definitions, the scope
//! vocabulary, every record's frontmatter, and the rules those records adopt.
//! It does not carry `HEADS.md`, and it does not carry a record's body.
//!
//! `HEADS.md` is derived state. `no-manual-index` exists because copied
//! derived state has no invariant behind it: nothing knows that a row which
//! should have been there is missing. Vendoring the projection would recreate
//! exactly that failure across repositories instead of inside one. Vendoring
//! the declarations means the consumer computes the heads itself, from the
//! same graph, with the same code — so a superseded decision cannot survive
//! the trip.
//!
//! A record's prose is left behind because it is written for the repository
//! that owns the decision, its citations point at that repository's files, and
//! the whole of it is an order of magnitude larger than the frontmatter that
//! actually answers a question.
//!
//! A **rule body** is the exception, and is not a counter-example to that. It
//! is a declaration in its own right — the translation of the rule the record
//! adopted — it is printed nowhere by default and is fetched by id when
//! somebody asks why, and a rule a consumer can list but not explain is one it
//! cannot apply. The "inert" paragraph of SEMANTICS section 2.3 governs what
//! happens when that text reaches a model, exactly as it does for a `choice`.
//!
//! # Nothing here executes
//!
//! This is the difference from `amont`'s packs, and it is why there is no
//! trust prompt to match `amont trust`. That tool vendors *commands*, so
//! consent has to be taken per machine and re-taken whenever the text changes.
//! A pack vendors *decisions*. Nothing in this file is ever run, so the review
//! gate is the pull request that adds it — which is where a change of
//! architectural direction belongs anyway.
//!
//! # Identity
//!
//! A pack's records keep their own ids and are qualified with the pack's name
//! on the way in: `ADR-0002` from the `decisions` pack is `decisions:ADR-0002`
//! here. Two repositories both numbering from one would otherwise collide, and
//! the collision would look like `id-unique` firing on a corpus whose author
//! wrote neither id. The qualification happens at load, not at vendor time, so
//! the file on disk stays what the producer published rather than something
//! this tool rewrote on the way in.

use crate::model::*;
use crate::yaml::{self, Node};

/// What a producing repository publishes, at its root.
pub const FILE: &str = "aval.pack";

pub const BANNER: &str = "Generated by `aval pack --write`. Do not edit.";

const PACK_FIELDS: &[&str] = &["aval", "scopes", "traits", "keys", "records", "rules"];
const RECORD_FIELDS: &[&str] = &["id", "status", "decisions"];
const RULE_FIELDS: &[&str] = &[
    "id",
    "level",
    "adopts",
    "source",
    "applies",
    "statement",
    "body",
];

fn a(check: &'static str, msg: impl Into<String>) -> Finding {
    Finding::new(Layer::A, check, msg)
}

/// `<pack>:<id>`, the form a vendored record is referred to by.
pub fn qualify(pack: &str, id: &str) -> String {
    format!("{}:{}", pack, id)
}

/// Whether a name can be a pack: it becomes an id prefix, so it has to be as
/// restricted as an id is, and it must not itself contain the separator.
pub fn bad_name(name: &str) -> Option<String> {
    if name.is_empty() {
        return Some("a pack name cannot be empty".into());
    }
    if name.len() > 32 {
        return Some(format!("pack name `{}` is longer than 32 characters", name));
    }
    if !name.starts_with(|c: char| c.is_ascii_alphabetic()) {
        return Some(format!("pack name `{}` must start with a letter", name));
    }
    if let Some(c) = name
        .chars()
        .find(|c| !(c.is_ascii_alphanumeric() || "._-".contains(*c)))
    {
        return Some(format!(
            "pack name `{}` carries `{}`; a name holds letters, digits, `.`, `_` and `-`",
            name, c
        ));
    }
    None
}

// --- writing ---------------------------------------------------------------

/// Emit a scalar that reads back as itself.
///
/// Always quoted, never bare. A bare `true` comes back a boolean, a bare `[a]`
/// a sequence, and a bare value holding `: ` is ambiguous with a mapping — and
/// the point of this file is that what the producer decided is what the
/// consumer reads. Quoting unconditionally costs two bytes and removes the
/// whole class.
///
/// Double quotes, unless the value holds more double quotes than single ones;
/// then single quotes, with `'` doubled. That is the choice prettier makes for
/// YAML, and it is now a **courtesy rather than a defence**. It was load-bearing
/// in 1.2.1, when the vendored copy was a `.yaml` a formatter would rewrite and
/// byte-equality was what said the file was still the published one. Neither
/// holds: a vendored pack is a `.pack`, which no formatter claims, and equality
/// is declarational (§2.3), so a requoted file has changed nothing anyone reads.
/// The quoting stays because it costs nothing and keeps a formatter quiet over
/// the producer's own `aval.pack` if a repository ever configures one to claim
/// that extension too.
fn out(s: &str) -> String {
    let doubles = s.matches('"').count();
    let singles = s.matches('\'').count();
    if doubles > singles {
        format!("'{}'", s.replace('\'', "''"))
    } else {
        format!("\"{}\"", s.replace('"', "\\\""))
    }
}

/// A block sequence, or `[]` when there is nothing to list.
///
/// A bare `scopes:` with no items reads back as an empty scalar, not as a
/// list, and the consumer refuses the whole pack with `pack-parses`. That is
/// the right refusal for a file it cannot read, and the wrong file to have
/// written: a registry with `scopes: []`, and a key with `scopes: []` — which
/// means "the default scope only" and is a declaration worth carrying — both
/// produced a pack nobody could load.
fn list(key: &str, items: &[&str], indent: &str) -> String {
    if items.is_empty() {
        return format!("{}: []\n", key);
    }
    let mut o = format!("{}:\n", key);
    for s in items {
        o.push_str(&format!("{}- {}\n", indent, out(s)));
    }
    o
}

/// The declarations of a corpus, as the text a consumer will vendor.
///
/// Deterministic and sorted, for the same reason `project::render` is: the file
/// is regenerated by a command and compared by a check, so any ordering that
/// depended on how the directory happened to be read would be a diff nobody
/// caused.
pub fn render(c: &Corpus) -> String {
    let mut o = String::new();
    o.push_str("# ");
    o.push_str(BANNER);
    o.push('\n');
    o.push_str(&format!("aval: {}\n", out(env!("CARGO_PKG_VERSION"))));

    let mut scopes: Vec<&str> = c.registry.scopes.iter().map(String::as_str).collect();
    scopes.sort();
    o.push_str(&list("scopes", &scopes, "  "));
    // The trait vocabulary (SEMANTICS section 2.5), only when there is one, so
    // a corpus that declares none publishes what it published before 1.7.0.
    // `registry.traits` is this corpus's own; what its packs lent it is in
    // `pack_traits` and is not re-exported.
    let mut traits: Vec<&str> = c.registry.traits.iter().map(String::as_str).collect();
    traits.sort();
    if !traits.is_empty() {
        o.push_str(&list("traits", &traits, "  "));
    }

    let mut keys: Vec<&KeyDef> = c.registry.keys.iter().collect();
    keys.sort_by(|x, y| x.name.cmp(&y.name));
    o.push_str("keys:\n");
    for k in &keys {
        o.push_str(&format!("  {}:\n", out(&k.name)));
        if let Some(d) = &k.description {
            o.push_str(&format!("    description: {}\n", out(d)));
        }
        if let Some(items) = &k.scopes {
            let mut v: Vec<&str> = items.iter().map(String::as_str).collect();
            v.sort();
            o.push_str(&list("    scopes", &v, "      "));
        }
    }

    let mut adrs: Vec<&Adr> = c.adrs.iter().collect();
    adrs.sort_by(|x, y| x.id.cmp(&y.id));
    o.push_str("records:\n");
    for r in &adrs {
        o.push_str(&format!("  - id: {}\n", out(r.id.as_str())));
        o.push_str(&format!(
            "    status: {}\n",
            out(match r.status {
                Status::Draft => "draft",
                Status::Accepted => "accepted",
            })
        ));
        o.push_str("    decisions:\n");
        for e in &r.decisions {
            o.push_str(&format!("      - key: {}\n", out(&e.key)));
            if e.scope != DEFAULT_SCOPE {
                o.push_str(&format!("        scope: {}\n", out(&e.scope)));
            }
            match &e.kind {
                EntryKind::Choice(ch) => o.push_str(&format!("        choice: {}\n", out(ch))),
                EntryKind::Retire => o.push_str("        retire: true\n"),
            }
            if e.is_first() {
                o.push_str("        first: true\n");
            }
            if !e.replaces().is_empty() {
                o.push_str("        replaces:\n");
                for p in e.replaces() {
                    o.push_str(&format!("          - {}\n", out(p.as_str())));
                }
            }
            if let Some(ov) = &e.overrides {
                o.push_str(&format!("        overrides: {}\n", out(ov.as_str())));
            }
            if let Some(rs) = &e.reason {
                o.push_str(&format!("        reason: {}\n", out(rs)));
            }
        }
    }

    // Rules last, because they refer to the records above them and a file is
    // read top to bottom by the person reviewing the diff. Omitted entirely
    // when there are none, so a corpus that declares no rules publishes the
    // same bytes it published before this existed.
    let mut rules: Vec<&Rule> = c.rules.iter().collect();
    rules.sort_by(|x, y| x.id.cmp(&y.id));
    if !rules.is_empty() {
        o.push_str("rules:\n");
        for r in &rules {
            o.push_str(&format!("  - id: {}\n", out(&r.id)));
            o.push_str(&format!("    level: {}\n", out(r.level.as_str())));
            o.push_str(&format!("    adopts: {}\n", out(r.adopts.as_str())));
            if let Some(s) = &r.source {
                o.push_str(&format!("    source: {}\n", out(s)));
            }
            if !r.applies.is_empty() {
                let v: Vec<&str> = r.applies.iter().map(String::as_str).collect();
                o.push_str(&list("    applies", &v, "      "));
            }
            o.push_str(&format!("    statement: {}\n", out(&r.statement)));
            if !r.body.is_empty() {
                o.push_str(&block(&r.body, 6));
            }
        }
    }
    o
}

/// A body as a literal block scalar, indented under `body:`.
///
/// Literal and not a quoted scalar, because a body is markdown with newlines in
/// it and the quoted form would need them escaped — unreadable in the diff that
/// is the review gate for a pack. A blank line inside it is emitted with no
/// trailing whitespace, so the file survives a formatter as well as §12.2 asks
/// `HEADS.md` to.
fn block(body: &str, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let mut o = format!("{}body: |\n", " ".repeat(indent - 2));
    for line in body.lines() {
        if line.is_empty() {
            o.push('\n');
        } else {
            o.push_str(&pad);
            o.push_str(line);
            o.push('\n');
        }
    }
    o
}

// --- reading ---------------------------------------------------------------

/// One pack, read and qualified.
#[derive(Debug, Clone)]
pub struct Pack {
    pub name: String,
    pub scopes: Vec<String>,
    pub traits: Vec<String>,
    pub keys: Vec<KeyDef>,
    pub adrs: Vec<Adr>,
    pub rules: Vec<Rule>,
}

fn want(node: &Node, key: &str, file: &str, out: &mut Vec<Finding>) -> Option<String> {
    let v = node.get(key)?;
    match v.as_str() {
        Some(s) => Some(s.to_string()),
        None => {
            out.push(
                a(
                    "pack-parses",
                    format!("`{}` must be a string, found {}", key, v.kind()),
                )
                .at(file, v.line),
            );
            None
        }
    }
}

fn want_list(node: &Node, key: &str, file: &str, out: &mut Vec<Finding>) -> Vec<String> {
    let Some(v) = node.get(key) else {
        return Vec::new();
    };
    let Some(items) = v.as_seq() else {
        out.push(
            a(
                "pack-parses",
                format!("`{}` must be a list, found {}", key, v.kind()),
            )
            .at(file, v.line),
        );
        return Vec::new();
    };
    items
        .iter()
        .filter_map(|i| match i.as_str() {
            Some(s) => Some(s.to_string()),
            None => {
                out.push(
                    a(
                        "pack-parses",
                        format!("`{}` must hold strings, found {}", key, i.kind()),
                    )
                    .at(file, i.line),
                );
                None
            }
        })
        .collect()
}

fn flag(node: &Node, key: &str) -> bool {
    node.get(key).and_then(|v| v.as_bool()).unwrap_or(false)
}

/// Read a vendored pack.
///
/// `file` is the vendored path in *this* repository, so every finding points
/// at something the reader can open. `name` is the pack's name, which becomes
/// the id prefix.
///
/// A pack is refused whole. A half-read pack is a graph that is missing edges
/// nobody removed: whatever a dropped record superseded comes back as a head,
/// and `resolve` answers `active` with a decision that was replaced. That is
/// the failure this tool exists to prevent, so it must not be reachable by a
/// file being slightly wrong.
pub fn parse(file: &str, name: &str, src: &str) -> Result<Pack, Vec<Finding>> {
    let mut out = Vec::new();
    if let Some(m) = bad_name(name) {
        return Err(vec![a("pack-parses", m).in_file(file)]);
    }
    let doc = match yaml::parse(src) {
        Ok(d) => d,
        Err(e) => return Err(vec![a("pack-parses", e.message).at(file, e.line)]),
    };
    if doc.as_map().is_none() {
        return Err(vec![a(
            "pack-parses",
            format!("a pack must be a mapping, found {}", doc.kind()),
        )
        .in_file(file)]);
    }
    for (k, v) in doc.as_map().unwrap() {
        if k == "areas" || k == "disclaims" {
            out.push(
                a(
                    "pack-parses",
                    format!(
                        "a pack carries no `{}`: it describes the producer's files, \
                         which no consumer has (SEMANTICS section 2.5)",
                        k
                    ),
                )
                .at(file, v.line),
            );
        } else if !PACK_FIELDS.contains(&k.as_str()) {
            out.push(a("pack-parses", format!("unknown pack field `{}`", k)).at(file, v.line));
        }
    }

    let scopes = want_list(&doc, "scopes", file, &mut out);
    let traits = want_list(&doc, "traits", file, &mut out);
    for t in &traits {
        if let Some(m) = crate::applicability::bad_trait(t) {
            out.push(a("pack-parses", m).at(file, doc.get("traits").map_or(1, |n| n.line)));
        }
    }
    let mut keys = Vec::new();
    if let Some(k) = doc.get("keys") {
        match k.as_map() {
            None if k.is_null() => {}
            None => out.push(
                a(
                    "pack-parses",
                    format!("`keys` must be a mapping, found {}", k.kind()),
                )
                .at(file, k.line),
            ),
            Some(entries) => {
                for (n, def) in entries {
                    let (description, key_scopes) = if def.is_null() {
                        (None, None)
                    } else {
                        (
                            want(def, "description", file, &mut out),
                            def.get("scopes")
                                .map(|_| want_list(def, "scopes", file, &mut out)),
                        )
                    };
                    keys.push(KeyDef {
                        name: n.clone(),
                        description,
                        scopes: key_scopes,
                    });
                }
            }
        }
    }

    // Every id in the pack, so an intra-pack reference can be told from a
    // dangling one before it is qualified. A reference that names nothing must
    // stay dangling rather than becoming a prefixed id that names nothing —
    // the finding would then blame a name the producer never wrote.
    let mut ids: Vec<String> = Vec::new();
    if let Some(rs) = doc.get("records").and_then(|r| r.as_seq()) {
        for r in rs {
            if let Some(i) = r.get("id").and_then(|n| n.as_str()) {
                ids.push(i.to_string());
            }
        }
    }
    // Qualify a reference only when it points INSIDE this pack; a dangling one
    // is left alone so the finding names what the document actually said.
    let q = |r: &str| -> AdrId {
        if ids.iter().any(|i| i == r) {
            AdrId::qualified(name, r)
        } else {
            AdrId::new(r)
        }
    };

    let mut adrs = Vec::new();
    match doc.get("records") {
        None => out.push(a("pack-parses", "missing `records`").in_file(file)),
        Some(r) if r.is_null() => {}
        Some(r) => match r.as_seq() {
            None => out.push(
                a(
                    "pack-parses",
                    format!("`records` must be a list, found {}", r.kind()),
                )
                .at(file, r.line),
            ),
            Some(items) => {
                for it in items {
                    if let Some(adr) = record(it, file, name, &q, &mut out) {
                        adrs.push(adr);
                    }
                }
            }
        },
    }

    let mut rules = Vec::new();
    match doc.get("rules") {
        // Absent is the ordinary case: a corpus that declares no rules
        // publishes what it always published.
        None => {}
        Some(r) if r.is_null() => {}
        Some(r) => match r.as_seq() {
            None => out.push(
                a(
                    "pack-parses",
                    format!("`rules` must be a list, found {}", r.kind()),
                )
                .at(file, r.line),
            ),
            Some(items) => {
                for it in items {
                    if let Some(rule) = rule(it, file, name, &q, &mut out) {
                        rules.push(rule);
                    }
                }
            }
        },
    }

    if out.is_empty() {
        Ok(Pack {
            name: name.to_string(),
            scopes,
            traits,
            keys,
            adrs,
            rules,
        })
    } else {
        Err(out)
    }
}

/// One vendored rule.
///
/// `adopts` is qualified exactly as `replaces` and `overrides` are, and only
/// when it names a record inside the pack: a rule whose adopting record is
/// missing from the file must keep the name the producer wrote, or the finding
/// blames an id nobody used.
fn rule(
    node: &Node,
    file: &str,
    pack: &str,
    q: &dyn Fn(&str) -> AdrId,
    out: &mut Vec<Finding>,
) -> Option<Rule> {
    let before = out.len();
    if node.as_map().is_none() {
        out.push(
            a(
                "pack-parses",
                format!("each rule must be a mapping, found {}", node.kind()),
            )
            .at(file, node.line),
        );
        return None;
    }
    for (k, v) in node.as_map().unwrap_or(&[]) {
        if !RULE_FIELDS.contains(&k.as_str()) {
            out.push(a("pack-parses", format!("unknown rule field `{}`", k)).at(file, v.line));
        }
    }
    let id = want(node, "id", file, out);
    if id.is_none() {
        out.push(a("pack-parses", "a rule is missing `id`").at(file, node.line));
    }
    if let Some(m) = id.as_deref().and_then(crate::rules::bad_id) {
        out.push(a("pack-parses", m).at(file, node.line));
    }
    let level = match want(node, "level", file, out) {
        Some(l) => match Level::parse(&l) {
            Some(x) => Some(x),
            None => {
                out.push(
                    a(
                        "pack-parses",
                        format!("`level: {}` is not `constraint` or `heuristic`", l),
                    )
                    .at(file, node.line),
                );
                None
            }
        },
        None => {
            out.push(a("pack-parses", "a rule is missing `level`").at(file, node.line));
            None
        }
    };
    let adopts = match want(node, "adopts", file, out) {
        Some(x) => Some(q(&x)),
        None => {
            out.push(a("pack-parses", "a rule is missing `adopts`").at(file, node.line));
            None
        }
    };
    let statement = match want(node, "statement", file, out) {
        Some(s) if !s.trim().is_empty() => Some(s),
        Some(_) => {
            out.push(a("pack-parses", "a rule has an empty `statement`").at(file, node.line));
            None
        }
        None => {
            out.push(a("pack-parses", "a rule is missing `statement`").at(file, node.line));
            None
        }
    };
    let source = want(node, "source", file, out);
    let applies = want_list(node, "applies", file, out);
    for t in &applies {
        if let Some(m) = crate::applicability::bad_trait(t) {
            out.push(a("pack-parses", m).at(file, node.line));
        }
    }
    // The clip newline a literal block scalar ends with is the block's, not the
    // body's: the body is stored trimmed, so render → parse → render is fixed.
    let body = want(node, "body", file, out)
        .map(|b| b.trim_end_matches('\n').to_string())
        .unwrap_or_default();

    if out.len() != before {
        return None;
    }
    let mut r = Rule::new(id?, level?, adopts?, statement?, file);
    r.body = body;
    r.source = source;
    r.applies = applies;
    r.pack = Some(pack.to_string());
    Some(r)
}

fn record(
    node: &Node,
    file: &str,
    pack: &str,
    q: &dyn Fn(&str) -> AdrId,
    out: &mut Vec<Finding>,
) -> Option<Adr> {
    let before = out.len();
    if node.as_map().is_none() {
        out.push(
            a(
                "pack-parses",
                format!("each record must be a mapping, found {}", node.kind()),
            )
            .at(file, node.line),
        );
        return None;
    }
    for (k, v) in node.as_map().unwrap() {
        if !RECORD_FIELDS.contains(&k.as_str()) {
            out.push(a("pack-parses", format!("unknown record field `{}`", k)).at(file, v.line));
        }
    }
    let id = want(node, "id", file, out);
    if id.is_none() {
        out.push(a("pack-parses", "a record is missing `id`").at(file, node.line));
    }
    let status = match want(node, "status", file, out) {
        Some(s) => match Status::parse(&s) {
            Some(st) => st,
            None => {
                out.push(
                    a("pack-parses", format!("`status: {}` is not a status", s))
                        .at(file, node.line),
                );
                Status::Draft
            }
        },
        None => {
            out.push(a("pack-parses", "a record is missing `status`").at(file, node.line));
            Status::Draft
        }
    };

    let mut decisions = Vec::new();
    if let Some(d) = node.get("decisions").and_then(|d| d.as_seq()) {
        for e in d {
            let key = match want(e, "key", file, out) {
                Some(k) => k,
                None => {
                    out.push(a("pack-parses", "a decision is missing `key`").at(file, e.line));
                    continue;
                }
            };
            let kind = match want(e, "choice", file, out) {
                Some(c) => EntryKind::Choice(c),
                None if flag(e, "retire") => EntryKind::Retire,
                None => {
                    out.push(
                        a(
                            "pack-parses",
                            "a decision has neither `choice` nor `retire`",
                        )
                        .at(file, e.line),
                    );
                    continue;
                }
            };
            let first = flag(e, "first");
            let replaces: Vec<AdrId> = want_list(e, "replaces", file, out)
                .iter()
                .map(|r| q(r))
                .collect();
            // A pack is generated and must not be edited by hand, but a
            // hand-edited one still reaches here. The old shape accepted
            // `first` and `replaces` together and carried the contradiction
            // into the graph; the sum type has nowhere to put it, so it is
            // refused with the rest of the pack.
            // Same shape as `parse`'s check, and named for the same reason:
            // the two agree only when the entry declared both or neither.
            let has_predecessor = !replaces.is_empty();
            if first == has_predecessor {
                out.push(
                    a(
                        "pack-readable",
                        format!(
                            "an entry for `{}` declares {}",
                            key,
                            if first {
                                "both `first` and `replaces`"
                            } else {
                                "neither `first` nor `replaces`"
                            }
                        ),
                    )
                    .at(file.to_string(), e.line),
                );
                continue;
            }
            decisions.push(Entry {
                key,
                scope: want(e, "scope", file, out).unwrap_or_else(|| DEFAULT_SCOPE.to_string()),
                kind,
                lineage: if first {
                    Lineage::First
                } else {
                    Lineage::Replaces(replaces)
                },
                overrides: want(e, "overrides", file, out).map(|o| q(&o)),
                reason: want(e, "reason", file, out),
                line: e.line,
            });
        }
    }

    if out.len() != before {
        return None;
    }
    Some(Adr {
        id: AdrId::qualified(pack, &id?),
        status,
        decisions,
        // The vendored file, because that is the file in this repository a
        // reader can open. The record's own document is in another one.
        file: file.to_string(),
        pack: Some(pack.to_string()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn corpus() -> Corpus {
        Corpus {
            registry: Registry {
                dir: "docs/adr".into(),
                sources: Vec::new(),
                packs: Vec::new(),
                rules: Vec::new(),
                scopes: vec!["effect-stack".into()],
                keys: vec![KeyDef {
                    name: "stack.sql-layer".into(),
                    description: Some("The SQL access layer".into()),
                    scopes: Some(vec!["effect-stack".into()]),
                }],
                traits: Vec::new(),
                pack_traits: Vec::new(),
                pack_scopes: Vec::new(),
                areas: Vec::new(),
                disclaims: Vec::new(),
            },
            rules: Vec::new(),
            adrs: vec![Adr {
                id: "ADR-0002".into(),
                status: Status::Accepted,
                decisions: vec![Entry {
                    key: "stack.sql-layer".into(),
                    scope: "effect-stack".into(),
                    kind: EntryKind::Choice("@effect/sql".into()),
                    lineage: Lineage::First,
                    overrides: None,
                    reason: Some("Kysely # was the alternative".into()),
                    line: 5,
                }],
                file: "docs/adr/0002-x.md".into(),
                pack: None,
            }],
        }
    }

    #[test]
    fn a_pack_round_trips() {
        let text = render(&corpus());
        let p = parse(".adr/packs/fleet.yaml", "fleet", &text).expect("parses");
        assert_eq!(p.scopes, ["effect-stack"]);
        assert_eq!(p.keys[0].name, "stack.sql-layer");
        assert_eq!(
            p.keys[0].scopes.as_deref(),
            Some(&["effect-stack".into()][..])
        );
        assert_eq!(p.adrs[0].id, "fleet:ADR-0002");
        assert!(p.adrs[0].is_vendored());
        let e = &p.adrs[0].decisions[0];
        assert_eq!(e.choice(), Some("@effect/sql"));
        assert_eq!(e.scope, "effect-stack");
        assert!(e.is_first());
        // The value carries ` # `, which an unquoted scalar would have lost to
        // the comment stripper. Quoting every value is what keeps it.
        assert_eq!(e.reason.as_deref(), Some("Kysely # was the alternative"));
    }

    #[test]
    fn empty_scope_lists_survive_the_trip() {
        // A registry with no scopes, and a key decided at the default scope
        // only. Both are legal declarations; both used to render as a bare
        // `scopes:` that read back as an empty scalar and refused the pack.
        let mut c = corpus();
        c.registry.scopes.clear();
        c.registry.keys[0].scopes = Some(Vec::new());
        c.adrs[0].decisions[0].scope = DEFAULT_SCOPE.into();
        let text = render(&c);
        assert!(text.contains("scopes: []\n"), "{}", text);
        assert!(text.contains("    scopes: []\n"), "{}", text);
        let p = parse(".adr/packs/fleet.yaml", "fleet", &text).expect("parses");
        assert!(p.scopes.is_empty());
        // `Some([])` and `None` are different declarations (SEMANTICS 2.1),
        // and the trip must not collapse one into the other.
        assert_eq!(p.keys[0].scopes.as_deref(), Some(&[][..]));
    }

    #[test]
    fn hostile_values_survive_the_trip() {
        let mut c = corpus();
        for (i, v) in [
            "a|b",
            "A\\|B",
            "back\\slash",
            "quote\"inside",
            "it's",
            "it's \"both\" here",
            "'leading and trailing'",
            "true",
            "[not, a, list]",
            "colon: here",
            "  padded  ",
            "# leading hash",
        ]
        .iter()
        .enumerate()
        {
            let mut r = c.adrs[0].clone();
            r.id = AdrId::new(format!("ADR-{:04}", 100 + i));
            r.decisions[0].kind = EntryKind::Choice((*v).to_string());
            c.adrs.push(r);
        }
        c.adrs.remove(0);
        let text = render(&c);
        let p = parse("p.yaml", "fleet", &text).expect("parses");
        let got: Vec<&str> = p
            .adrs
            .iter()
            .filter_map(|r| r.decisions[0].choice())
            .collect();
        assert_eq!(
            got,
            [
                "a|b",
                "A\\|B",
                "back\\slash",
                "quote\"inside",
                "it's",
                "it's \"both\" here",
                "'leading and trailing'",
                "true",
                "[not, a, list]",
                "colon: here",
                "  padded  ",
                "# leading hash",
            ]
        );
    }

    #[test]
    fn quoting_is_the_style_prettier_would_choose() {
        // A courtesy to formatters since 1.3, not a defence: the vendored file
        // is a `.pack` and equality is declarational. More double quotes than
        // single: single-quoted, with the single quote doubled. Otherwise
        // double-quoted.
        assert_eq!(out("plain"), "\"plain\"");
        assert_eq!(out("say \"hi\""), "'say \"hi\"'");
        assert_eq!(out("it's"), "\"it's\"");
        assert_eq!(out("it's \"both\" here"), "'it''s \"both\" here'");
        assert_eq!(out("a \"b\" 'c' 'd'"), "\"a \\\"b\\\" 'c' 'd'\"");
    }

    #[test]
    fn intra_pack_references_are_qualified_and_dangling_ones_are_not() {
        let mut c = corpus();
        let mut r = c.adrs[0].clone();
        r.id = "ADR-0003".into();
        r.decisions[0].lineage = Lineage::Replaces(vec!["ADR-0002".into(), "ADR-9999".into()]);
        c.adrs.push(r);
        let p = parse("p.yaml", "fleet", &render(&c)).expect("parses");
        let second = p.adrs.iter().find(|x| x.id == "fleet:ADR-0003").unwrap();
        assert_eq!(
            second.decisions[0].replaces(),
            ["fleet:ADR-0002", "ADR-9999"],
            "a reference that names nothing must stay as written, or the \
             finding would blame a name the producer never used"
        );
    }

    #[test]
    fn a_pack_is_refused_whole_on_one_bad_record() {
        let text = render(&corpus()).replace("\"accepted\"", "\"superseded\"");
        let e = parse("p.yaml", "fleet", &text).unwrap_err();
        assert!(e[0].message.contains("is not a status"), "{:?}", e);
    }

    /// A body with blank lines, a markdown sub-heading and no trailing newline:
    /// the three things the block-scalar path used to lose silently.
    #[test]
    fn a_rule_round_trips_including_its_body() {
        let mut c = corpus();
        let mut r = Rule::new(
            "names.reveal-intent",
            Level::Constraint,
            AdrId::new("ADR-0002"),
            "Names reveal intention: a reader never decodes an abbreviation.",
            "docs/principles/clean-code.md",
        );
        r.body =
            "Why, first.\n\n### The translation\n\n- one\n- two\n\nLast line, no newline after it."
                .into();
        r.source = Some("Clean Code (Robert C. Martin, 2008)".into());
        let second = Rule::new(
            "a.b",
            Level::Heuristic,
            AdrId::new("ADR-0002"),
            "Sorted before the other one, whatever order it was pushed in.",
            "docs/principles/clean-code.md",
        );
        c.rules = vec![r.clone(), second];

        let text = render(&c);
        let p = parse(".adr/packs/fleet.yaml", "fleet", &text).expect("parses");
        assert_eq!(p.rules.len(), 2);
        assert_eq!(p.rules[0].id, "a.b", "rules are sorted by id");
        let got = &p.rules[1];
        assert_eq!(got.id, r.id);
        assert_eq!(got.level, Level::Constraint);
        assert_eq!(got.statement, r.statement);
        assert_eq!(got.body, r.body);
        assert_eq!(got.source, r.source);
        // Qualified on the way in, like every other reference into the pack.
        assert_eq!(got.adopts, "fleet:ADR-0002");
        assert_eq!(got.file, ".adr/packs/fleet.yaml");
        assert_eq!(got.pack.as_deref(), Some("fleet"));
        // No body at all is not an empty body's worth of bytes.
        assert_eq!(p.rules[0].body, "");
        assert!(!text.contains("    body: |\n    level"), "{}", text);
    }

    #[test]
    fn a_corpus_with_no_rules_emits_no_rules_section() {
        assert!(!render(&corpus()).contains("rules:"));
    }

    #[test]
    fn a_rule_that_adopts_nothing_in_the_pack_keeps_the_name_as_written() {
        let mut c = corpus();
        c.rules = vec![Rule::new(
            "a.b",
            Level::Constraint,
            AdrId::new("ADR-9999"),
            "One.",
            "r.md",
        )];
        let p = parse("p.yaml", "fleet", &render(&c)).expect("parses");
        assert_eq!(p.rules[0].adopts, "ADR-9999");
    }

    #[test]
    fn a_pack_is_refused_whole_on_one_bad_rule() {
        let mut c = corpus();
        c.rules = vec![Rule::new(
            "a.b",
            Level::Constraint,
            AdrId::new("ADR-0002"),
            "One.",
            "r.md",
        )];
        let text = render(&c).replace("\"constraint\"", "\"advisory\"");
        let e = parse("p.yaml", "fleet", &text).unwrap_err();
        assert!(e[0].message.contains("is not `constraint`"), "{:?}", e);

        let text = render(&c).replace("\"a.b\"", "\"No.pe\"");
        let e = parse("p.yaml", "fleet", &text).unwrap_err();
        assert!(e[0].message.contains("lowercase"), "{:?}", e);
    }

    #[test]
    fn a_pack_name_must_be_usable_as_an_id_prefix() {
        assert!(bad_name("decisions").is_none());
        assert!(bad_name("").is_some());
        assert!(bad_name("2fleet").is_some());
        // The separator itself, which would make the prefix ambiguous.
        assert!(bad_name("a:b").is_some());
    }
}
