//! `HEADS.md`: the projection.
//!
//! Deliberately dull. Sorted, no timestamp, no prose, no history, so CI can
//! regenerate it and byte-compare. It renders only heads, so a superseded entry
//! cannot appear in it, and it is never written at all when the graph failed
//! Layer A: a partial projection would be a false statement of current state
//! wearing the authority of a generated file.

use crate::graph::Graph;
use crate::model::{Slot, DEFAULT_SCOPE};

pub const HEADER: &str = "# Architecture decision heads";
pub const BANNER: &str = "Generated by `aval heads --write`. Do not edit.";

/// Markdown table cells carry `|`, which would split the row.
fn cell(s: &str) -> String {
    s.replace('|', "\\|")
}

fn scope_cell(scope: &str) -> String {
    if scope == DEFAULT_SCOPE {
        "—".to_string()
    } else {
        cell(scope)
    }
}

pub fn render(g: &Graph) -> String {
    let mut active: Vec<(String, String, String, String)> = Vec::new();
    let mut retired: Vec<(String, String, String)> = Vec::new();

    for slot in g.corpus().slots() {
        let h = g.heads(slot);
        // More than one head is a contradiction, and a projection must not
        // quietly print one of them. `check` reports it; `heads` stays silent
        // rather than picking.
        let [(adr, entry)] = h[..] else { continue };
        match entry.choice() {
            Some(c) => active.push((
                slot.key.to_string(),
                slot.scope.to_string(),
                adr.id.clone(),
                c.to_string(),
            )),
            None => retired.push((slot.key.to_string(), slot.scope.to_string(), adr.id.clone())),
        }
    }

    let decided: Vec<&str> = g
        .corpus()
        .slots()
        .iter()
        .filter(|s| !g.heads(**s).is_empty())
        .map(|s| s.key)
        .collect();
    let mut undecided: Vec<&str> = g
        .registry()
        .keys
        .iter()
        .map(|k| k.name.as_str())
        .filter(|k| !decided.contains(k))
        .collect();

    active.sort();
    retired.sort();
    undecided.sort();

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n");
    out.push_str(BANNER);
    out.push_str("\n\n## Active\n\n");
    if active.is_empty() {
        out.push_str("None.\n");
    } else {
        out.push_str("| Key | Scope | ADR | Decision |\n|---|---|---|---|\n");
        for (k, s, a, c) in &active {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                cell(k),
                scope_cell(s),
                a,
                cell(c)
            ));
        }
    }

    out.push_str("\n## Undecided\n\n");
    if undecided.is_empty() {
        out.push_str("None.\n");
    } else {
        for k in &undecided {
            out.push_str(&format!("- {}\n", cell(k)));
        }
    }

    out.push_str("\n## Retired\n\n");
    if retired.is_empty() {
        out.push_str("None.\n");
    } else {
        out.push_str("| Key | Scope | ADR |\n|---|---|---|\n");
        for (k, s, a) in &retired {
            out.push_str(&format!("| {} | {} | {} |\n", cell(k), scope_cell(s), a));
        }
    }
    out
}

/// Slots that would be rendered, for callers that want the data not the text.
pub fn head_slots(g: &Graph) -> Vec<Slot<'_>> {
    g.corpus()
        .slots()
        .into_iter()
        .filter(|s| g.heads(*s).len() == 1)
        .collect()
}
