//! `HEADS.md`: the projection.
//!
//! Deliberately dull. Sorted, no timestamp, no prose, no history, so CI can
//! regenerate it and byte-compare. It renders only heads, so a superseded entry
//! cannot appear in it, and it is never written at all when the graph failed
//! Layer A: a partial projection would be a false statement of current state
//! wearing the authority of a generated file.

use crate::graph::Graph;
use crate::model::{Slot, DEFAULT_SCOPE};

pub const HEADER: &str = "# Architecture decision heads";
pub const BANNER: &str = "Generated by `aval heads --write`. Do not edit.";

/// Markdown table cells carry `|`, which would split the row.
///
/// The backslash is escaped first, and that order is the whole correctness
/// argument: escaping only `|` turned the choice `A\|B` into `A\\|B`, which a
/// reader counting backslashes sees as an unescaped pipe and splits on,
/// producing a five-column row from a four-column one.
///
/// A newline cannot appear here — `parse` rejects one in `choice` and `reason`
/// before it ever reaches the projection — because there is no escape for it
/// in a markdown table row, and one would split a record across several.
fn cell(s: &str) -> String {
    s.trim().replace('\\', "\\\\").replace('|', "\\|")
}

fn scope_cell(scope: &str) -> String {
    if scope == DEFAULT_SCOPE {
        "—".to_string()
    } else {
        cell(scope)
    }
}

pub fn render(g: &Graph) -> String {
    let mut active: Vec<(String, String, String, String)> = Vec::new();
    let mut retired: Vec<(String, String, String)> = Vec::new();

    for slot in g.corpus().slots() {
        let h = g.heads(slot);
        // More than one head is a contradiction, and a projection must not
        // quietly print one of them. `check` reports it; `heads` stays silent
        // rather than picking.
        let [(adr, entry)] = h[..] else { continue };
        match entry.choice() {
            Some(c) => active.push((
                slot.key.to_string(),
                slot.scope.to_string(),
                adr.id.clone(),
                c.to_string(),
            )),
            None => retired.push((slot.key.to_string(), slot.scope.to_string(), adr.id.clone())),
        }
    }

    let decided: Vec<&str> = g
        .corpus()
        .slots()
        .iter()
        .filter(|s| !g.heads(**s).is_empty())
        .map(|s| s.key)
        .collect();
    let mut undecided: Vec<&str> = g
        .registry()
        .keys
        .iter()
        .map(|k| k.name.as_str())
        .filter(|k| !decided.contains(k))
        .collect();

    active.sort();
    retired.sort();
    undecided.sort();

    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n");
    out.push_str(BANNER);
    out.push_str("\n\n## Active\n\n");
    if active.is_empty() {
        out.push_str("None.\n");
    } else {
        out.push_str("| Key | Scope | Record | Decision |\n|---|---|---|---|\n");
        for (k, s, a, c) in &active {
            out.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                cell(k),
                scope_cell(s),
                a,
                cell(c)
            ));
        }
    }

    out.push_str("\n## Undecided\n\n");
    if undecided.is_empty() {
        out.push_str("None.\n");
    } else {
        for k in &undecided {
            out.push_str(&format!("- {}\n", cell(k)));
        }
    }

    out.push_str("\n## Retired\n\n");
    if retired.is_empty() {
        out.push_str("None.\n");
    } else {
        out.push_str("| Key | Scope | Record |\n|---|---|---|\n");
        for (k, s, a) in &retired {
            out.push_str(&format!("| {} | {} | {} |\n", cell(k), scope_cell(s), a));
        }
    }
    out
}

/// Slots that would be rendered, for callers that want the data not the text.
pub fn head_slots(g: &Graph) -> Vec<Slot<'_>> {
    g.corpus()
        .slots()
        .into_iter()
        .filter(|s| g.heads(*s).len() == 1)
        .collect()
}

/// Normalise away the differences a markdown formatter makes, and nothing else.
///
/// `HEADS.md` lives in repositories that run prettier, dprint or mdformat over
/// their markdown, and those pad table cells and rewrite the delimiter row.
/// Byte comparison called that stale forever. Comparing *canonicalised* forms
/// instead accepts the formatting and still rejects every edit that changes
/// what the file says.
///
/// This is deliberately a whitelist rather than a parser. A reader that turned
/// the file into rows and compared those would ignore whatever it did not
/// model, so a paragraph added under the banner — or a banner rewritten to say
/// the file is maintained by hand — would compare equal and pass forever.
/// Anything not named below survives into the comparison and shows up as a
/// difference, which is the property byte comparison had and the one worth
/// keeping.
///
/// Applied to both sides, so it never has to decode an escape correctly: a
/// mistake in `cell()` is made identically to the file and to the render.
pub fn canonicalise(text: &str) -> String {
    let text = text.strip_prefix('\u{feff}').unwrap_or(text);
    let mut out = String::with_capacity(text.len());
    for line in text.replace("\r\n", "\n").lines() {
        let line = line.trim_end();
        out.push_str(&canonical_row(line));
        out.push('\n');
    }
    // `render` ends in exactly one newline; a formatter may leave none or
    // several, and neither says anything.
    while out.ends_with("\n\n") {
        out.pop();
    }
    out
}

/// A table row with its padding removed, or the line unchanged.
///
/// The delimiter row collapses to `|---|` per column, so `| :--- |` and
/// `|---|` agree. Column *alignment* markers are dropped with the padding:
/// the projection never emits one, so a file carrying one differs from the
/// render in a way no formatter introduced.
fn canonical_row(line: &str) -> String {
    let t = line.trim();
    if !t.starts_with('|') || !t.ends_with('|') || t.len() < 2 {
        return line.to_string();
    }
    let inner = &t[1..t.len() - 1];
    let fields: Vec<&str> = split_unescaped(inner);
    let mut out = String::from("|");
    for f in fields {
        let f = f.trim();
        if is_delimiter_field(f) {
            out.push_str("---|");
        } else {
            out.push_str(f);
            out.push('|');
        }
    }
    out
}

/// `---`, `:---`, `---:` or `:---:` — the shapes a formatter writes for the
/// row under a table header.
fn is_delimiter_field(f: &str) -> bool {
    let core = f.trim_start_matches(':').trim_end_matches(':');
    !core.is_empty() && core.chars().all(|c| c == '-')
}

/// Split on `|` that is not escaped. A `|` is escaped when an odd number of
/// backslashes precedes it, which is why `cell()` has to escape the backslash.
fn split_unescaped(s: &str) -> Vec<&str> {
    let b = s.as_bytes();
    let mut out = Vec::new();
    let mut start = 0;
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'|' {
            let mut back = 0;
            let mut j = i;
            while j > start && b[j - 1] == b'\\' {
                back += 1;
                j -= 1;
            }
            if back % 2 == 0 {
                out.push(&s[start..i]);
                start = i + 1;
            }
        }
        i += 1;
    }
    out.push(&s[start..]);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const CANON: &str = "\
# Architecture decision heads

Generated by `aval heads --write`. Do not edit.

## Active

| Key | Scope | Record | Decision |
|---|---|---|---|
| a.b | — | ADR-0001 | One |
| c.d | cloud | ADR-0002 | Two |

## Undecided

None.

## Retired

None.
";

    fn same(a: &str, b: &str) -> bool {
        canonicalise(a) == canonicalise(b)
    }

    #[test]
    fn padding_and_delimiter_style_are_formatting() {
        // What prettier actually does: pad every cell to the column width and
        // rewrite `|---|` as `| --- |`.
        let pretty = CANON.replace(
            "| Key | Scope | Record | Decision |\n|---|---|---|---|\n\
                 | a.b | — | ADR-0001 | One |\n| c.d | cloud | ADR-0002 | Two |",
            "| Key | Scope | Record   | Decision |\n\
                 | --- | ----- | -------- | -------- |\n\
                 | a.b | —     | ADR-0001 | One      |\n\
                 | c.d | cloud | ADR-0002 | Two      |",
        );
        assert_ne!(pretty, CANON, "the fixture must actually differ");
        assert!(same(&pretty, CANON));
    }

    #[test]
    fn alignment_markers_are_formatting() {
        let aligned = CANON.replace("|---|---|---|---|", "| :--- | ---: | :---: | --- |");
        assert!(same(&aligned, CANON));
    }

    #[test]
    fn line_endings_bom_and_trailing_space_are_formatting() {
        // CRLF must be tolerated rather than repaired: a Windows checkout with
        // autocrlf would otherwise be stale, get rewritten as LF, be converted
        // back on checkout, and never converge.
        assert!(same(&CANON.replace('\n', "\r\n"), CANON));
        assert!(same(&format!("\u{feff}{}", CANON), CANON));
        assert!(same(&CANON.replace(" |\n", " |   \n"), CANON));
        assert!(same(&format!("{}\n\n\n", CANON), CANON));
        assert!(same(CANON.trim_end(), CANON));
    }

    #[test]
    fn a_changed_row_is_not_formatting() {
        assert!(!same(&CANON.replace("ADR-0001", "ADR-0009"), CANON));
        assert!(!same(
            &CANON.replace("| One |", "| Something else |"),
            CANON
        ));
    }

    #[test]
    fn an_added_or_removed_row_is_not_formatting() {
        assert!(!same(
            &CANON.replace("| c.d | cloud | ADR-0002 | Two |\n", ""),
            CANON
        ));
        assert!(!same(
            &CANON.replace(
                "| c.d | cloud | ADR-0002 | Two |\n",
                "| c.d | cloud | ADR-0002 | Two |\n| e.f | — | ADR-0003 | Three |\n",
            ),
            CANON
        ));
    }

    #[test]
    fn reordering_is_not_formatting() {
        // The projection is sorted (section 12). If a reordering were fresh,
        // nothing would enforce the sort any more.
        let swapped = CANON.replace(
            "| a.b | — | ADR-0001 | One |\n| c.d | cloud | ADR-0002 | Two |",
            "| c.d | cloud | ADR-0002 | Two |\n| a.b | — | ADR-0001 | One |",
        );
        assert!(!same(&swapped, CANON));
    }

    /// The trap a semantic reader would fall into: prose it does not model is
    /// prose it ignores, so the edit passes forever and an idempotent write
    /// then preserves it.
    #[test]
    fn added_prose_and_an_edited_banner_are_not_formatting() {
        assert!(!same(
            &CANON.replace("## Undecided", "Note: under review.\n\n## Undecided"),
            CANON
        ));
        assert!(!same(
            &CANON.replace("Do not edit.", "Maintained by hand."),
            CANON
        ));
        assert!(!same(
            &CANON.replace("## Retired", "## Retired decisions"),
            CANON
        ));
    }

    #[test]
    fn an_em_dash_a_formatter_replaced_is_not_formatting() {
        // No formatter should do this, and if one does the answer is to notice
        // rather than to guess that `--` meant the default scope.
        assert!(!same(&CANON.replace(" — ", " -- "), CANON));
    }

    #[test]
    fn a_pipe_in_a_cell_survives_and_a_backslash_before_it_does_too() {
        // `cell()` escapes the backslash first, so these are decodable. The
        // canonicaliser never has to decode them — it is applied to both sides
        // — but a wrong split must not merge two columns into one either.
        assert_eq!(cell("A|B"), "A\\|B");
        assert_eq!(cell("A\\|B"), "A\\\\\\|B");
        assert_eq!(split_unescaped(" a \\| b | c "), vec![" a \\| b ", " c "]);
        assert_eq!(cell("  padded  "), "padded");
    }
}
